apiVersion: v1
kind: ConfigMap
metadata:
  name: ml-service-config
  namespace: ml-service
data:
  MINIO_ENDPOINT: "minio:9000"
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_SECRET_KEY: "minioadmin"
  MINIO_SECURE: "false"
  CLEARML_API_HOST: "http://host.minikube.internal:8008"
  CLEARML_WEB_HOST: "http://host.minikube.internal:8080"
  DVC_REMOTE: "minio"
  DVC_CACHE_DIR: ".dvc/cache"
  MODELS_DIR: "models"
  DATASETS_DIR: "data"

