apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ml-service

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - minio/pvc.yaml
  - minio/deployment.yaml
  - minio/service.yaml
  - minio/job-init.yaml
  - api/pvc.yaml
  - api/deployment.yaml
  - api/service.yaml
  - grpc/deployment.yaml
  - grpc/service.yaml
  - dashboard/deployment.yaml
  - dashboard/service.yaml


